- name : Shell Vs Command Modules
  hosts: local
  connection : local
  become: yes
  tasks:
  - name : Command module example for checking the date
    ansible.builtin.command: date
    register: date
    register: current_date
  - name : "Executing the Command module for current date"
    ansible.builtin.debug:
      msg : | 
      Date : "Today date is {{date.stdout}}"
      Current_date: {{current_date}}