- name: demo on loops
  hosts: local
  connection : local
  become : yes
  tasks:
  - name: "Printing names which are in the loops"
    ansible.builtin.package:
      msg: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
#ansible-playbook -i inventory.ini 17.loops_install_packages.yml