- name : Types of Variables
  hosts: local
  become : yes
  connection: local #if we will give connection local not needed to provide username and password while running the ansible code
  #for running ansible-playbook -i inventory.ini 4.Variables.yml
  vars : #defining variables in vars which means it is declared as globally and we ca use it any where
    Course: "Devops"
    Topic : "Ansible"
    Date : "22-Feb-2026"
  tasks :
  - name : "Printing the statement by using variables"
    ansible.builtin.debug:
      msg : "I’m learning {{ Course }}, focusing on {{ Topic }} today, on {{ Date }}"
  - name: Insalling nginx
    ansible.builtin.package:
      name : nginx
      state : present
  - name : Start nginx
  #to start the service ansible.builtin.service module is default
    ansible.builtin.service:
      name : nginx
      state: started
      enabled : yes

